import type { Channel, LocalMessage, StreamChat } from 'stream-chat';

import type { ChatContextValue } from '../../../context';
import type { TranslationContextValue } from '../../../context/TranslationContext';
import {
  type AccessibleLabelConfig,
  type AccessibleLabelPart,
  activeLabelPart,
  composeAccessibleLabel,
  unreadCountLabelPart,
} from '../../../a11y/accessibleLabel';
import { getDateString, isDate } from '../../../i18n/utils';

/**
 * Everything a label part needs. Gathered by `ThreadListItemUI` from the thread state + contexts and
 * handed to each {@link ThreadListItemLabelPart}.
 */
export type ThreadListItemLabelData = {
  /** Whether the row is the active (currently open) thread. */
  active?: boolean;
  /** The channel the thread belongs to. */
  channel?: Channel;
  /** Client, used to detect whether a message is the current user's own. */
  client: StreamChat;
  /** The channel's display name (the thread row's title). */
  displayTitle?: string;
  isMessageAIGenerated?: ChatContextValue['isMessageAIGenerated'];
  /** The most recent reply in the thread. */
  latestReply?: LocalMessage;
  /** The message the thread is attached to (its subject); available for custom parts. */
  parentMessage?: LocalMessage;
  /**
   * The parent message's display preview text — the SAME string the visible subtitle shows (from
   * `useLatestMessagePreview`, covering text/attachment/poll/etc.). Used by the default
   * `parentMessage` part so the announcement matches what is shown.
   */
  parentMessagePreview?: string;
  /** The parent message's sender prefix, when the visible preview shows one (e.g. "You", a name). */
  parentMessageSender?: string;
  /** Number of participants in the thread. */
  participantCount?: number;
  /** Number of replies in the thread. */
  replyCount?: number;
  t: TranslationContextValue['t'];
  tDateTimeParser: TranslationContextValue['tDateTimeParser'];
  /** The current user's unread reply count for the thread. */
  unreadCount?: number;
  userLanguage?: TranslationContextValue['userLanguage'];
};

/** Produces one segment of the accessible name; return `undefined`/empty to omit it. */
export type ThreadListItemLabelPart = AccessibleLabelPart<ThreadListItemLabelData>;

/**
 * The default, named label parts. Each is independently overridable via
 * {@link ThreadListItemLabelConfig.parts}. The active (currently open) state is announced here (not
 * left to the row's `aria-selected` alone, which is not reliably spoken across screen readers for an
 * option with a custom name); `aria-selected` is kept on the active row for listbox semantics.
 */
export const defaultThreadListItemLabelParts = {
  active: activeLabelPart,
  name: ({ displayTitle, t }) =>
    displayTitle
      ? t('aria/Chat: {{ channelName }}', { channelName: displayTitle })
      : undefined,
  // The message the thread is about (shown as the row's subtitle); same preview the subtitle shows.
  parentMessage: ({ parentMessagePreview, parentMessageSender, t }) => {
    if (!parentMessagePreview) return undefined;
    const preview = parentMessageSender
      ? `${parentMessageSender}: ${parentMessagePreview}`
      : parentMessagePreview;
    return t('aria/Thread: {{ messagePreview }}', { messagePreview: preview });
  },
  replyCount: ({ replyCount, t }) =>
    typeof replyCount === 'number' && replyCount > 0
      ? t('replyCount', { count: replyCount })
      : undefined,
  time: ({ latestReply, t, tDateTimeParser }) => {
    const createdAt = latestReply?.created_at;
    if (!createdAt || !isDate(createdAt)) return undefined;
    const when = getDateString({
      messageCreatedAt: createdAt.toISOString(),
      t,
      tDateTimeParser,
      timestampTranslationKey: 'timestamp/ChannelPreviewTimestamp',
    });
    return when ? t('aria/Last activity: {{ time }}', { time: String(when) }) : undefined;
  },
  unreadCount: unreadCountLabelPart,
} satisfies Record<string, ThreadListItemLabelPart>;

/** Default order the parts are assembled in (reading order). */
export const DEFAULT_THREAD_LIST_ITEM_LABEL_ORDER = [
  'name',
  'active',
  'unreadCount',
  'parentMessage',
  'replyCount',
  'time',
] as const;

export type ThreadListItemLabelConfig = AccessibleLabelConfig<ThreadListItemLabelData>;

/**
 * Composes a single, coherent accessible name for a thread list row from named parts. The default
 * reading order is name (channel) → active → unread → parent message → reply count → last activity.
 *
 * ## Customizing the label
 *
 * The label is generated by `ThreadListItemUI`, which accepts an `accessibleLabelConfig` prop. To
 * customize it, supply your own `ThreadListItemUI` through `ComponentContext` (the same way the
 * component is overridden) and forward the config — no new plumbing:
 *
 * ```tsx
 * const MyThreadListItemUI = (props) => (
 *   <DefaultThreadListItemUI {...props} accessibleLabelConfig={accessibleLabelConfig} />
 * );
 * // <ComponentProvider value={{ ThreadListItemUI: MyThreadListItemUI }}> … </ComponentProvider>
 * ```
 *
 * ### Adding custom parts
 *
 * - {@link ThreadListItemLabelConfig.parts} is merged over {@link defaultThreadListItemLabelParts},
 *   so a new key is *added* and a same-named key *overrides* the default.
 * - A part returns its segment string, or `undefined`/`''` to be omitted.
 * - {@link ThreadListItemLabelConfig.order} decides which parts are included AND their sequence —
 *   **a part not listed in `order` is never rendered**. Spread
 *   {@link DEFAULT_THREAD_LIST_ITEM_LABEL_ORDER} to keep the defaults and insert your own.
 * - Each part receives {@link ThreadListItemLabelData}. Parts call `t`, so provide your own i18n keys
 *   (or return plain strings).
 *
 * ```tsx
 * const accessibleLabelConfig: ThreadListItemLabelConfig = {
 *   parts: {
 *     participants: ({ participantCount, t }) =>
 *       participantCount ? t('{{ count }} participants', { count: participantCount }) : undefined,
 *   },
 *   order: ['name', 'participants', ...DEFAULT_THREAD_LIST_ITEM_LABEL_ORDER.slice(1)],
 * };
 * ```
 *
 * For full control, set {@link ThreadListItemLabelConfig.build} (return the entire string), or write
 * a custom `ThreadListItemUI` that calls this function directly — importing
 * {@link defaultThreadListItemLabelParts} to reuse the built-ins.
 */
export const composeThreadListItemAccessibleLabel = (
  data: ThreadListItemLabelData,
  config: ThreadListItemLabelConfig = {},
): string =>
  composeAccessibleLabel(
    data,
    defaultThreadListItemLabelParts,
    DEFAULT_THREAD_LIST_ITEM_LABEL_ORDER,
    config,
  );
