'use strict';

var _interopRequireDefault = require('@babel/runtime/helpers/interopRequireDefault');

Object.defineProperty(exports, '__esModule', {
  value: true,
});
exports.default = void 0;

var _react = _interopRequireDefault(require('react'));

var _propTypes = _interopRequireDefault(require('prop-types'));

/**
 * AttachmentActions - The actions you can take on an attachment
 *
 * @example ../../docs/AttachmentActions.md
 * @type {React.FC<import('type').AttachmentActionsProps>}
 */
var AttachmentActions = function AttachmentActions(_ref) {
  var text = _ref.text,
    id = _ref.id,
    actions = _ref.actions,
    actionHandler = _ref.actionHandler;
  return /*#__PURE__*/ _react.default.createElement(
    'div',
    {
      className: 'str-chat__message-attachment-actions',
    },
    /*#__PURE__*/ _react.default.createElement(
      'div',
      {
        className: 'str-chat__message-attachment-actions-form',
      },
      /*#__PURE__*/ _react.default.createElement(
        'span',
        {
          key: 0,
        },
        text,
      ),
      actions.map(function (action) {
        return /*#__PURE__*/ _react.default.createElement(
          'button',
          {
            className: 'str-chat__message-attachment-actions-button str-chat__message-attachment-actions-button--'.concat(
              action.style,
            ),
            'data-testid': ''.concat(action.name),
            key: ''.concat(id, '-').concat(action.value),
            'data-value': action.value,
            onClick: function onClick(e) {
              return actionHandler(action.name, action.value, e);
            },
          },
          action.text,
        );
      }),
    ),
  );
};

AttachmentActions.propTypes = {
  /** Unique id for action button key. Key is generated by concatenating this id with action value - {`${id}-${action.value}`} */
  id: _propTypes.default.string.isRequired,

  /** The text for the form input */
  text: _propTypes.default.string,

  /** A list of actions */
  actions: _propTypes.default.array.isRequired,

  /**
   *
   * @param name {string} Name of action
   * @param value {string} Value of action
   * @param event Dom event that triggered this handler
   */
  actionHandler: _propTypes.default.func.isRequired,
};

var _default = /*#__PURE__*/ _react.default.memo(AttachmentActions);

exports.default = _default;
