name: Setup
description: Sets up Node and installs dependencies

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        cache: 'yarn'
        node-version-file: '.nvmrc'

    - name: Set NODE_VERSION env
      shell: bash
      run: echo "NODE_VERSION=$(node --version)" >> $GITHUB_ENV

    - name: Install dependencies
      run: yarn install
      shell: bash
