yarnPath: .yarn/releases/yarn-4.14.1.cjs
nodeLinker: node-modules
nmMode: hardlinks-global
enableHardenedMode: true
enableScripts: false
enableGlobalCache: true
enableTelemetry: false
initScope: stream-io
npmMinimalAgeGate: 3d
npmPublishProvenance: true
