enableGlobalCache: true

enableScripts: false

enableTelemetry: false

initScope: stream-io

nmMode: hardlinks-global

nodeLinker: node-modules

npmMinimalAgeGate: 1d

npmPreapprovedPackages:
  - stream-chat
  - vite

npmPublishProvenance: true

yarnPath: .yarn/releases/yarn-4.15.0.cjs
