enableGlobalCache: true

enableHardenedMode: true

enableScripts: false

enableTelemetry: false

initScope: stream-io

nmMode: hardlinks-global

nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPublishProvenance: true

yarnPath: .yarn/releases/yarn-4.15.0.cjs

npmPreapprovedPackages:
  - stream-chat
