export default {
  addMessageButton: 'data-testid=add-message',
  channelHeader: '.str-chat__header-livestream',
  channelList: '.str-chat__channel-list-messenger__main',
  channelPreviewButton: '[data-testid=channel-preview-button]',
  message: '.str-chat__message',
  messageInput: 'data-testid=message-input',
  messageList: '.str-chat__list',
  messagesInMessageList: '.str-chat__ul > li',
  messageNotification: '.str-chat__message-notification',
  messageSimple: '.str-chat__message-simple',
  messageWithText: '.str-chat__message--has-text',
  quotedMessage: '.quoted-message',
  textMessage: '.str-chat__message-text',
  truncateChannelButton: 'data-testid=truncate',
};
