export default {
  buttonAddMessage: 'data-testid=add-message',
  buttonCloseThread: 'button[aria-label="Close thread"]',
  buttonOpenThread: 'button[aria-label="Open Thread"]',
  buttonOpenActionsBox: 'button[aria-label="Open Message Actions Menu"]',
  channelHeader: '.str-chat__header-livestream',
  channelList: '.str-chat__channel-list-messenger__main',
  channelPreviewButton: '[data-testid=channel-preview-button]',
  channelPreviewLastMessage: '.str-chat__channel-preview-messenger--last-message',
  controlsBtnDeleteLastReply: 'data-testid=delete-last-reply',
  message: '.str-chat__message',
  messageActionsBox: '.str-chat__message-actions-box',
  messageInput: 'data-testid=message-input',
  messageInputTextareaThread: '.str-chat__small-message-input [data-testid="message-input"]',
  messageList: '.str-chat__list',
  messagesInMessageList: '.str-chat__ul > li',
  messageNotification: '.str-chat__message-notification',
  messageRepliesButton: '.str-chat__message-simple-reply-button',
  messageSimple: '.str-chat__message-simple',
  messageWithText: '.str-chat__message--has-text',
  quotedMessage: '.quoted-message',
  textMessage: '.str-chat__message-text',
  threadMessageList: '.str-chat__thread-list',
  threadReplyList: '.str-chat__list--thread',
  threadReplyListWithReplies: '.str-chat__list--thread ul',
  threadStart: '.str-chat__thread-start',
  truncateChannelButton: 'data-testid=truncate',
};
