export default {
  attachmentCard: '.str-chat__message-attachment--card',
  attachmentGallery: '.str-chat__message-attachment--gallery',
  attachmentImage: '.str-chat__message-attachment--img',
  avatar: '.str-chat__avatar',
  buttonAddMessage: 'data-testid=add-message',
  buttonAddOtherUserMessage: 'data-testid=add-other-user-message',
  buttonCancel: 'text=Cancel',
  buttonCancelUpload: '.str-chat__attachment-preview-delete',
  buttonCloseThread: 'button[aria-label="Close thread"]',
  buttonOpenActionsBox: 'button[aria-label="Open Message Actions Menu"]',
  buttonOpenThread: 'button[aria-label="Open Thread"]',
  buttonSend: 'text=Send',
  buttonSendOtherUserReply: 'button[data-testid=receive-reply]',
  channelHeader: '.str-chat__header-livestream',
  channelList: '.str-chat__channel-list-messenger__main',
  channelPreviewButton: '[data-testid=channel-preview-button]',
  channelPreviewLastMessage: '.str-chat__channel-preview-messenger--last-message',
  controlsBtnDeleteLastReply: 'data-testid=delete-last-reply',
  controlsBtnDeleteOtherUserLastMessage: 'data-testid=delete-other-last-message',
  controlsBtnDeleteOtherUserLastReply: 'data-testid=delete-other-last-reply',
  message: '.str-chat__message',
  messageActionsBox: '.str-chat__message-actions-box--open',
  messageData: `.str-chat__message-data`,
  messageInput: 'data-testid=message-input',
  messageInputTextareaThread: '.str-chat__message-input [data-testid="message-input"]',
  messageList: '.str-chat__ul',
  messageListContainer: '.str-chat__list',
  messageNotification: '.str-chat__message-notification',
  messageRepliesButton: '.str-chat__message-simple-reply-button',
  messageSimple: '.str-chat__message-simple',
  messagesInMessageList: '.str-chat__ul > li',
  messageText: '[data-testid=message-text-inner-wrapper]',
  messageTimestamp: '.str-chat__message-simple-timestamp',
  messageWithText: '.str-chat__message--has-text',
  modalOpen: '.str-chat__modal--open',
  pinnedMessagesList: 'data-testid=pinned-messages-list',
  quotedMessage: '.quoted-message',
  textMessage: '.str-chat__message-text',
  threadHeader: '.str-chat__thread-header',
  threadMessageList: '.str-chat__thread-list',
  threadReplyList: '.str-chat__list--thread',
  threadReplyListWithReplies: '.str-chat__list--thread ul',
  threadStart: '.str-chat__thread-start',
  truncateChannelButton: 'data-testid=truncate',
};
