// Generates src/i18n/keys.ts from src/i18n/en.json.
//
// The output is *type-only* on purpose: it declares the catalog as a mapped type rather than a
// runtime object, so it costs nothing in the bundle while still letting `tsc` emit a
// self-contained .d.ts. (Deriving the type from `typeof import('./en.json')` would not work for
// consumers — tsc does not copy JSON into dist/types, so the import is unresolvable there.)
//
// Run by `yarn build-translations`, after extraction.
//
// `.mts` rather than `.ts`: the package has no `"type": "module"`, so Node would treat a plain
// `.ts` file as CommonJS and reject these `import` statements. Node 24 strips the types at run
// time; `yarn types:scripts` is what actually checks them.
import fs from 'node:fs';

const IN = 'src/i18n/en.json';
const OUT = 'src/i18n/keys.ts';

type Catalog = Record<string, unknown>;

const catalog = JSON.parse(fs.readFileSync(IN, 'utf8')) as Catalog;
const keys = Object.keys(catalog).sort();

const lines: string[] = [
  '// AUTO-GENERATED by scripts/generate-i18n-keys.mts — do not edit by hand.',
  '// Regenerate with `yarn build-translations`. CI fails if this file is out of sync.',
  '//',
  '// Type-only: no runtime value is emitted, so this adds nothing to the bundle.',
  '',
  '/**',
  ' * Every translation entry shipped with the SDK, mapped to its English copy.',
  ' *',
  ' * Plural entries appear as `<key>_one` / `<key>_other`; call sites use the bare `<key>` and',
  ' * pass `count`. See {@link TranslationKey}.',
  ' */',
  'export type TranslationCatalog = {',
];

let entryCount = 0;
for (const key of keys) {
  const value = catalog[key];
  if (typeof value !== 'string') continue;
  lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(value)};`);
  entryCount++;
}
lines.push('};', '');

fs.writeFileSync(OUT, lines.join('\n'));
console.log(`generated ${OUT} (${entryCount} entries)`);
