// Generates the two files derived from src/i18n/en.json:
//
//   src/i18n/keys.ts            type-only catalog of every key -> its English copy. No runtime
//                               value, so it costs nothing in the bundle. (Deriving the type from
//                               `typeof import('./en.json')` would not work for consumers — tsc
//                               does not copy JSON into dist/types.)
//   src/i18n/runtimeDefaults.ts the *only* translation data that ships. Just the keys that have no
//                               inline copy at their call site and therefore cannot fall back to a
//                               `defaultValue`: `language.*` (resolved from a runtime code),
//                               `timestamp.*` / `duration.*` (formatter expressions passed around
//                               as prop values), and the postProcessor directive.
//
// en.json itself is NOT bundled. It is the complete reference — what a translator or TMS consumes,
// and the source for keys.ts — but every prose key renders from the inline copy at its call site,
// so shipping the JSON too would duplicate ~40 KB of strings already present in the code.
//
// Run by `yarn build-translations`, after extraction and the en.json sync.
import fs from 'node:fs';
import { readCallSiteCopy } from './i18n-call-sites.mts';

const EN = 'src/i18n/en.json';
const KEYS_OUT = 'src/i18n/keys.ts';
const RUNTIME_OUT = 'src/i18n/runtimeDefaults.ts';

type Catalog = Record<string, unknown>;

const catalog = JSON.parse(fs.readFileSync(EN, 'utf8')) as Catalog;
const keys = Object.keys(catalog).sort();
const { copy: inlineCopy } = readCallSiteCopy();

// ---------------------------------------------------------------------------------------
// keys.ts — types for every key
// ---------------------------------------------------------------------------------------
const keyLines: string[] = [
  '// AUTO-GENERATED by scripts/generate-i18n-keys.mts — do not edit by hand.',
  '// Regenerate with `yarn build-translations`. CI fails if this file is out of sync.',
  '//',
  '// Type-only: no runtime value is emitted, so this adds nothing to the bundle.',
  '',
  '/**',
  ' * Every translation entry shipped with the SDK, mapped to its English copy.',
  ' *',
  ' * Plural entries appear as `<key>_one` / `<key>_other`; call sites use the bare `<key>` and',
  ' * pass `count`. See {@link TranslationKey}.',
  ' */',
  'export type TranslationCatalog = {',
];
let typed = 0;
for (const key of keys) {
  const value = catalog[key];
  if (typeof value !== 'string') continue;
  keyLines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(value)};`);
  typed++;
}
keyLines.push('};', '');
fs.writeFileSync(KEYS_OUT, keyLines.join('\n'));

// ---------------------------------------------------------------------------------------
// runtimeDefaults.ts — the subset that has to ship
// ---------------------------------------------------------------------------------------
const runtimeKeys = keys.filter(
  (key) => typeof catalog[key] === 'string' && !inlineCopy.has(key),
);

const runtimeLines: string[] = [
  '// AUTO-GENERATED by scripts/generate-i18n-keys.mts — do not edit by hand.',
  '// Regenerate with `yarn build-translations`. CI fails if this file is out of sync.',
  '',
  '/**',
  ' * The only translation data bundled with the SDK.',
  ' *',
  ' * Every *prose* key passes its English copy inline at the call site',
  " * (`t('message.status.sent.text', 'Sent')`), so i18next renders it from that `defaultValue` and",
  ' * the string does not need to ship twice. The keys below have no inline copy to fall back on:',
  ' *',
  ' * - `language.*` — the key is built from a runtime language code',
  ' * - `timestamp.*`, `duration.*` — formatter expressions, passed around as prop values',
  ' * - `translationBuilderTopic.*` — an i18next postProcessor directive',
  ' *',
  ' * The complete key reference, for translators, is `src/i18n/en.json`.',
  ' */',
  'export const runtimeDefaults = {',
];
for (const key of runtimeKeys) {
  runtimeLines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(catalog[key])},`);
}
runtimeLines.push('};', '');
fs.writeFileSync(RUNTIME_OUT, runtimeLines.join('\n'));

console.log(`generated ${KEYS_OUT} (${typed} entries, type-only)`);
console.log(
  `generated ${RUNTIME_OUT} (${runtimeKeys.length} bundled entries; ` +
    `${typed - runtimeKeys.length} render from inline copy)`,
);
