import type { ComponentPropsWithoutRef, ComponentType } from 'react';

export type IconComponent = ComponentType<ComponentPropsWithoutRef<'svg'>>;

/**
 * Names of icons that can be overridden via `ComponentContext.icons`. Enumerated from icons
 * actually imported from `../components/Icons` anywhere in `src/`. Overrides are deep-merged
 * with sibling entries by `WithComponents`, so a consumer can rebrand a single icon without
 * clearing the others.
 */
export type IconSlots = Partial<
  Record<
    | 'IconArchive'
    | 'IconArrowDown'
    | 'IconArrowDownCircle'
    | 'IconArrowLeft'
    | 'IconArrowUp'
    | 'IconArrowUpRight'
    | 'IconAttachment'
    | 'IconAudio'
    | 'IconBell'
    | 'IconBellOff'
    | 'IconBolt'
    | 'IconBookmark'
    | 'IconBookmarkRemove'
    | 'IconCamera'
    | 'IconCheckmark'
    | 'IconCheckmark1Small'
    | 'IconChecks'
    | 'IconChevronDown'
    | 'IconChevronLeft'
    | 'IconChevronRight'
    | 'IconClock'
    | 'IconCommand'
    | 'IconCopy'
    | 'IconDelete'
    | 'IconDownload'
    | 'IconEdit'
    | 'IconEmoji'
    | 'IconEmojiAdd'
    | 'IconExclamationCircleFill'
    | 'IconExclamationMark'
    | 'IconExclamationMarkFill'
    | 'IconExclamationTriangleFill'
    | 'IconEyeFill'
    | 'IconFile'
    | 'IconFlag'
    | 'IconFolder'
    | 'IconGiphy'
    | 'IconImage'
    | 'IconInfo'
    | 'IconLeave'
    | 'IconLink'
    | 'IconLoading'
    | 'IconLocation'
    | 'IconMegaphone'
    | 'IconMenu'
    | 'IconMessageBubble'
    | 'IconMessageBubbleFill'
    | 'IconMessageBubbles'
    | 'IconMicrophoneSolid'
    | 'IconMinus'
    | 'IconMinusCircle'
    | 'IconMore'
    | 'IconMute'
    | 'IconNoSign'
    | 'IconNotification'
    | 'IconPauseFill'
    | 'IconPin'
    | 'IconPlayFill'
    | 'IconPlus'
    | 'IconPlusSmall'
    | 'IconPoll'
    | 'IconQuote'
    | 'IconRefresh'
    | 'IconReorder'
    | 'IconReply'
    | 'IconRetry'
    | 'IconSearch'
    | 'IconSend'
    | 'IconShield'
    | 'IconThread'
    | 'IconThreadFill'
    | 'IconTranslate'
    | 'IconTrophy'
    | 'IconUnpin'
    | 'IconUnsupportedAttachment'
    | 'IconUpload'
    | 'IconUser'
    | 'IconUserAdd'
    | 'IconUserCheck'
    | 'IconUserRemove'
    | 'IconUsers'
    | 'IconVideo'
    | 'IconVideoFill'
    | 'IconVoice'
    | 'IconXmark'
    | 'IconXmarkSmall',
    IconComponent
  >
>;
