name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: ESLint & Prettier
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node

      - run: yarn lint

  build:
    runs-on: ubuntu-latest
    name: Build & Validate
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node

      - run: yarn build

      - name: Validate CJS bundle with Node ${{ env.NODE_VERSION }}
        run: yarn validate-cjs

      - name: Validate translations
        run: yarn validate-translations

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node

      - name: Test with Node ${{ env.NODE_VERSION }}
        run: yarn coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy-vite-example:
    runs-on: ubuntu-latest
    # skip if build fails
    needs:
      - build
    name: Deploy Vite Example to Vercel
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: prj_2Rq8kuNd0BmqKd2NwvkDjX9Htnx5
      VITE_STREAM_API_KEY: ${{ vars.VITE_STREAM_API_KEY }}
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node
        env:
          NODE_ENV: ""

      - name: Build SDK
        run: yarn build

      - name: Install example dependencies
        working-directory: examples/vite
        run: yarn install --frozen-lockfile
        shell: bash

      - name: Vercel Pull/Build/Deploy (Preview)
        working-directory: examples/vite
        if: ${{ github.ref_name != 'master' }}
        run: >
          npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} &&
          npx vercel build &&
          npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      - name: Vercel Pull/Build/Deploy (Production)
        working-directory: examples/vite
        if: ${{ github.ref_name == 'master' }}
        run: >
          npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} &&
          npx vercel build --prod &&
          npx vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
