name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - master

env:
  BUILD_CACHE_KEY: ${{ github.sha }}-dist
jobs:
  lint:
    runs-on: ubuntu-latest
    name: ESLint & Prettier
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node

      - run: yarn lint

  build:
    runs-on: ubuntu-latest
    name: Build & Validate
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node

      - run: yarn build

      - name: Validate CJS bundle with Node ${{ env.NODE_VERSION }}
        run: yarn validate-cjs

      - name: Validate translations
        run: yarn validate-translations

      - name: Cache Build Output
        uses: actions/cache@v5
        with:
          path: ./dist
          key: '${{ env.BUILD_CACHE_KEY }}'

  test:
    if: ${{ github.ref_name != 'master' }}
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node

      - name: Test with Node ${{ env.NODE_VERSION }}
        run: yarn coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy-vite-example:
    concurrency:
      cancel-in-progress: true
      # one deployment per PR, not commit
      group: "${{ github.base_ref || github.ref_name }}:${{ github.head_ref || 'nil' }}:${{matrix.projects.project-id}}"
    strategy:
      matrix:
        projects:
          - name: Vite Example Development
            project-id: prj_2Rq8kuNd0BmqKd2NwvkDjX9Htnx5
            stream-api-key: rq7ntdb4zzsq
          - name: Vite Example Public
            project-id: prj_yBYBe1AJV0tbpTqxCMzcyRfFWXxP
            stream-api-key: xzwhhgtazy6h
    runs-on: ubuntu-latest
    environment:
      name: "${{ matrix.projects.name }} (${{ github.ref_name == 'master' && 'Production' || 'Preview' }})"
      deployment: true
      url: '${{ steps.deploy-to-vercel.outputs.deploy-url }}'
    # skip if build fails
    needs:
      - build
    name: Deploy Vite Example to Vercel
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ matrix.projects.project-id }}
      VITE_STREAM_API_KEY: ${{ matrix.projects.stream-api-key }}
      NODE_ENV: production
      DEPLOY_TARGET: ${{ github.ref_name == 'master' && 'production' || 'preview' }}
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node
        env:
          NODE_ENV: ''

      - name: Recover Build Output
        id: build-cache
        uses: actions/cache@v5
        with:
          path: ./dist
          key: '${{ env.BUILD_CACHE_KEY }}'

      - name: Build SDK
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: yarn build

      - name: Install example dependencies
        working-directory: examples/vite
        run: yarn install --frozen-lockfile
        shell: bash

      - name: Vercel Pull/Build/Deploy
        working-directory: examples/vite
        id: deploy-to-vercel
        run: >-
          npx vercel pull --yes --environment=${{ env.DEPLOY_TARGET }} --token=${{ secrets.VERCEL_TOKEN }} &&
          npx vercel build --target=${{ env.DEPLOY_TARGET }} &&
          npx vercel deploy --target=${{ env.DEPLOY_TARGET }} --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | 
          xargs -I % echo "deploy-url=%" >> "$GITHUB_OUTPUT"
