name: Check PR title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: commitlint
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint --verbose
