name: PR Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node

      - run: echo "${{ github.event.pull_request.title }}" | npx commitlint --verbose
